#!/bin/sh

# Set Default Values
XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-"$HOME"/.config}"
XDG_CACHE_HOME="${XDG_CACHE_HOME:-"$HOME"/.cache}"
XDG_DATA_HOME="${XDG_DATA_HOME:-"$HOME"/.local/share}"

userresources=$XDG_CONFIG_HOME/X11/xresources
usermodmap=$XDG_CONFIG_HOME/X11/xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# Change Xorg cache files
export USERXSESSION="$XDG_CACHE_HOME/X11/xsession"
export USERXSESSIONRC="$XDG_CACHE_HOME/X11/xsessionrc"
export ALTUSERXSESSION="$XDG_CACHE_HOME/X11/Xsession"
export ERRFILE="$XDG_CACHE_HOME/X11/xsession-errors"

# merge in defaults and keymaps

if [ -f "$sysresources" ]; then
	xrdb -merge "$sysresources" &
fi

if [ -f "$sysmodmap" ]; then
	xmodmap "$sysmodmap" &
fi

if [ -f "$userresources" ]; then
	xrdb -merge "$userresources" &
fi

if [ -f "$usermodmap" ]; then
	xmodmap "$usermodmap" &
fi

# Disable screen blanking after 10 minues
xset -dpms &
xset s off &

numlockx & # Enable numlock

# Start Window Manager
case "${XDG_CURRENT_DESKTOP:=Awesome}" in
'Awesome')
    export XDG_CURRENT_DESKTOP
	export WINDOW_MANAGER='awesome'
	;;
'i3')
	export WINDOW_MANAGER='i3'
	;;
esac

export PINENTRY_USER_DATA='gtk'
systemctl --user import-environment XDG_CURRENT_DESKTOP PINENTRY_USER_DATA

if [ "$WINDOW_MANAGER" ]; then
	exec "${WINDOW_MANAGER:=awesome}"
fi
