#!/bin/sh

userresources=$XDG_CONFIG_HOME/X11/xresources
usermodmap=$XDG_CONFIG_HOME/X11/xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# Change Xorg cache files
export USERXSESSION="$XDG_CACHE_HOME/X11/xsession"
export USERXSESSIONRC="$XDG_CACHE_HOME/X11/xsessionrc"
export ALTUSERXSESSION="$XDG_CACHE_HOME/X11/Xsession"
export ERRFILE="$XDG_CACHE_HOME/X11/xsession-errors"

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources &
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap &
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources" &
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap" &
fi

# Disable screen blanking after 10 minues
xset -dpms &
xset s off &

# Core System Functionality
dunst &    # Notification daemon
numlockx & # Enable numlock
picom -b & # Compositor
sxhkd &    # Hotkey Daemon
xwallpaper --zoom /usr/share/backgrounds/archlinux/awesome.png & # Wallpaper
/usr/bin/pipewire &       # Audio Server
/usr/bin/pipewire-pulse & # Pulse Server
/usr/bin/wireplumber &    # Pipewire Media Manager

# Program Autostart
signal-desktop --start-in-tray &
# KeePassXC.desktop
# com.nextcloud.desktopclient.nextcloud.desktop
# newsboat.desktop
# qutebrowser.desktop
# thunderbird.desktop

# Start Window Manager
exec i3
