#!/bin/sh

userresources=$XDG_CONFIG_HOME/X11/xresources
usermodmap=$XDG_CONFIG_HOME/X11/xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# Change Xorg cache files
export USERXSESSION="$XDG_CACHE_HOME/X11/xsession"
export USERXSESSIONRC="$XDG_CACHE_HOME/X11/xsessionrc"
export ALTUSERXSESSION="$XDG_CACHE_HOME/X11/Xsession"
export ERRFILE="$XDG_CACHE_HOME/X11/xsession-errors"

# merge in defaults and keymaps

if [ -f "$sysresources" ]; then
	xrdb -merge "$sysresources" &
fi

if [ -f "$sysmodmap" ]; then
	xmodmap "$sysmodmap" &
fi

if [ -f "$userresources" ]; then
	xrdb -merge "$userresources" &
fi

if [ -f "$usermodmap" ]; then
	xmodmap "$usermodmap" &
fi

# Disable screen blanking after 10 minues
xset -dpms &
xset s off &

numlockx & # Enable numlock

# Program Autostart
signal-desktop --start-in-tray &
"$HOME"/.local/bin/autostart.sh &

# Service Manager
dinit --log-file "$XDG_DATA_HOME"/dinit/dinit.log &

# Start Window Manager
exec i3
