local function define_augroup(name, autocmds)
	vim.cmd("augroup " .. name)
	vim.cmd("autocmd!")
    autocmds()
	vim.cmd("augroup END")
end

define_augroup("OpenFolds", function()
	vim.cmd("autocmd BufRead * silent! %foldopen!")
end)

define_augroup("FTApperance", function()
	vim.cmd("autocmd FileType c setlocal tabstop=8 shiftwidth=8 noexpandtab")
	vim.cmd("autocmd FileType haskell setlocal tabstop=2 shiftwidth=2")
	vim.cmd("autocmd FileType markdown setlocal tabstop=2 shiftwidth=2 textwidth=80")
	vim.cmd("autocmd TermOpen * setlocal nonumber norelativenumber")
end)

define_augroup("DispatchCompiler", function()
	vim.cmd("autocmd FileType java let b:dispatch = 'gradle build'")
	vim.cmd("autocmd FileType python let b:dispatch = 'mypy %'")
	vim.cmd("autocmd FileType markdown let b:dispatch = 'pandoc --pdf-engine=xelatex -f markdown % -o %.pdf'")
	vim.cmd("autocmd FileType tex let b:dispatch = 'latexmk -pvc -pdflua %'")
	vim.cmd("autocmd FileType plaintex let b:dispatch = 'latexmk -pvc -pdf %'")
end)

define_augroup("TemplateFiles", function()
	vim.cmd("autocmd BufNewFile *.py  0r ~/.config/nvim/templates/skeleton.py")
	vim.cmd("autocmd BufNewFile *.zsh 0r ~/.config/nvim/templates/skeleton.zsh")
end)

define_augroup("TrimWhiteSpace", function ()
    vim.cmd("autocmd BufWritePre *.md :%s/\\s\\+$//e")
    vim.cmd("autocmd BufWritePre *.py :%s/\\s\\+$//e")
end)
