#!/bin/sh

# This is the example configuration file for river.
#
# If you wish to edit this, you will probably want to copy it to
# $XDG_CONFIG_HOME/river/init or $HOME/.config/river/init first.
#
# See the river(1), riverctl(1), and rivertile(1) man pages for complete
# documentation.

systemctl --user import-environment DISPLAY XAUTHORITY
systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

src="$(dirname -- "$0")"

. "$src"/keybindings

. "$src"/theme

. "$src"/inputs

. "$src"/statusbar

# Set keyboard repeat rate
riverctl set-repeat 50 300

systemctl --user start plasma-polkit-agent.service &
sleep 5 && systemctl --user start river-xdg-autostart.target &
