#!/bin/sh

userresources=$XDG_CONFIG_HOME/xresources
usermodmap=$XDG_CONFIG_HOME/xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# Autostart programs in $XDG_CONFIG_HOME/autostart
dex --autostart --environment i3 &

# Start Window Manager
exec i3
