# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Left prompt
format = "$time$directory$git_branch$git_status$sudo$status$character"
right_format = "$all"
add_newline = false

# Timeout after 200ms (Fast or Bust)
# command_timeout = 200

[cmd_duration]
min_time = 500
show_milliseconds = true

[time]
format = "[$time](bold yellow) "
disabled = false

[status]
format = "[$signal_name$common_meaning$maybe_int](red)"
symbol = "[✗](bold red)"
disabled = false

[sudo]
disabled = false
