#!/usr/bin/zsh
# Enviromnet variables
export QT_QPA_PLATFORMTHEME='qt5ct'

# Run ssh-agent if it hasn't been launched
if [ -z "$SSH_AUTH_SOCK" ]; then
    eval "$(ssh-agent)"
fi

# Start X server if on tty1 or tty2
if [ -z "${DISPLAY}" ] && [ "${XDG_VTNR}" -le 2 ]; then
    # Create Xauthority file
    touch $XAUTHORITY

    # Run dbus if it hasn't been launched
    if [ -z "$DBUS_SESSION_BUS_ADDRESS" ]; then
        export DBUS_SESSION_BUS_ADDRESS="$(dbus-daemon --session --syslog-only --print-address --fork --address=unix:path=$XDG_RUNTIME_DIR/dbus)"
    fi

    export PINENTRY_USER_DATA='gtk'

    # Select Window Manager
    if [ "$XDG_VTNR" -eq 2 ]; then
        export WINDOW_MANAGER='awesome'
    else
        export WINDOW_MANAGER='i3'
    fi

    # Start X server
    xinit -- :"$XDG_VTNR"
    logout
elif [ -z "${DISPLAY}" ] && [ "${XDG_VTNR}" -eq 7 ]; then
    # Logging in using Ly

    # Create Xauthority file
    touch $XAUTHORITY

    # Run dbus if it hasn't been launched
    if [ -z "$DBUS_SESSION_BUS_ADDRESS" ]; then
        export DBUS_SESSION_BUS_ADDRESS="$(dbus-daemon --session --syslog-only --print-address --fork --address=unix:path=$XDG_RUNTIME_DIR/dbus)"
    fi

    export PINENTRY_USER_DATA='gtk'

    # Select Window Manager
    export WINDOW_MANAGER='awesome'

    # Start X server
    xinit -- :"$XDG_VTNR"
    logout
elif [ -z "${DISPLAY}" ] && [ "${XDG_VTNR}" -gt 2 ]; then
    # Service Manager
    dinit --log-file "$XDG_DATA_HOME"/dinit/dinit.log>/dev/null&
    alias logout='dinitctl shutdown && logout'
fi
